DROP INDEX IF EXISTS path_idx;
DROP INDEX IF EXISTS path_gist_idx;

DROP TABLE IF EXISTS object_comment;
DROP TABLE IF EXISTS slice_translation;
DROP TABLE IF EXISTS slice_expression;
DROP TABLE IF EXISTS group_slice;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS texts;
DROP TABLE IF EXISTS translations;
DROP TABLE IF EXISTS expressions;
DROP TABLE IF EXISTS object_types;
DROP TABLE IF EXISTS slices;
DROP TABLE IF EXISTS user_group;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS languages;

DROP EXTENSION IF EXISTS ltree;
DROP TRIGGER IF EXISTS updated_at ON users;
DROP TRIGGER IF EXISTS updated_at ON slices;
DROP TRIGGER IF EXISTS updated_at ON comments;
DROP TRIGGER IF EXISTS updated_at ON texts;
DROP FUNCTION IF EXISTS trigger_set_timestamp;
