DROP INDEX IF EXISTS path_idx;
DROP INDEX IF EXISTS path_gist_idx;

DROP TABLE IF EXISTS training_items;
DROP TABLE IF EXISTS trainings;
DROP TABLE IF EXISTS object_comment;
DROP TABLE IF EXISTS node_translation;
DROP TABLE IF EXISTS node_expression;
DROP TABLE IF EXISTS group_node;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS nodes;
DROP TABLE IF EXISTS texts;
DROP TABLE IF EXISTS translations;
DROP TABLE IF EXISTS expressions;
DROP TABLE IF EXISTS object_types;
DROP TABLE IF EXISTS user_group;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS languages;

DROP EXTENSION IF EXISTS ltree;
DROP EXTENSION IF EXISTS pg_trgm;
DROP TRIGGER IF EXISTS updated_at ON users;
DROP TRIGGER IF EXISTS updated_at ON nodes;
DROP TRIGGER IF EXISTS updated_at ON comments;
DROP TRIGGER IF EXISTS updated_at ON texts;
DROP FUNCTION IF EXISTS trigger_set_timestamp;
